class BARREL:
    """Barrel SS values for MC 1.21.5. The only difference from mcschematic.BlockDataDB.BARREL is that the 'count' now lowercase. Does not work otherwise."""
    _barrelSS = [
        """minecraft:barrel[open=false,facing=up]{CustomName:'0',Items:[{count:0b,Slot:0b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'1',Items:[{count:1b,Slot:0b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'2',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:60b,Slot:1b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'3',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:55b,Slot:3b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'4',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:51b,Slot:5b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'5',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:46b,Slot:7b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'6',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:42b,Slot:9b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'7',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:37b,Slot:11b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'8',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:32b,Slot:13b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'9',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:28b,Slot:15b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'10',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:64b,Slot:15b,id:"minecraft:redstone"},{count:64b,Slot:16b,id:"minecraft:redstone"},{count:23b,Slot:17b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'11',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:64b,Slot:15b,id:"minecraft:redstone"},{count:64b,Slot:16b,id:"minecraft:redstone"},{count:64b,Slot:17b,id:"minecraft:redstone"},{count:64b,Slot:18b,id:"minecraft:redstone"},{count:19b,Slot:19b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'12',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:64b,Slot:15b,id:"minecraft:redstone"},{count:64b,Slot:16b,id:"minecraft:redstone"},{count:64b,Slot:17b,id:"minecraft:redstone"},{count:64b,Slot:18b,id:"minecraft:redstone"},{count:64b,Slot:19b,id:"minecraft:redstone"},{count:64b,Slot:20b,id:"minecraft:redstone"},{count:14b,Slot:21b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'13',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:64b,Slot:15b,id:"minecraft:redstone"},{count:64b,Slot:16b,id:"minecraft:redstone"},{count:64b,Slot:17b,id:"minecraft:redstone"},{count:64b,Slot:18b,id:"minecraft:redstone"},{count:64b,Slot:19b,id:"minecraft:redstone"},{count:64b,Slot:20b,id:"minecraft:redstone"},{count:64b,Slot:21b,id:"minecraft:redstone"},{count:64b,Slot:22b,id:"minecraft:redstone"},{count:10b,Slot:23b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'14',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:64b,Slot:15b,id:"minecraft:redstone"},{count:64b,Slot:16b,id:"minecraft:redstone"},{count:64b,Slot:17b,id:"minecraft:redstone"},{count:64b,Slot:18b,id:"minecraft:redstone"},{count:64b,Slot:19b,id:"minecraft:redstone"},{count:64b,Slot:20b,id:"minecraft:redstone"},{count:64b,Slot:21b,id:"minecraft:redstone"},{count:64b,Slot:22b,id:"minecraft:redstone"},{count:64b,Slot:23b,id:"minecraft:redstone"},{count:64b,Slot:24b,id:"minecraft:redstone"},{count:5b,Slot:25b,id:"minecraft:redstone"}]}""",
        """minecraft:barrel[open=false,facing=up]{CustomName:'15',Items:[{count:64b,Slot:0b,id:"minecraft:redstone"},{count:64b,Slot:1b,id:"minecraft:redstone"},{count:64b,Slot:2b,id:"minecraft:redstone"},{count:64b,Slot:3b,id:"minecraft:redstone"},{count:64b,Slot:4b,id:"minecraft:redstone"},{count:64b,Slot:5b,id:"minecraft:redstone"},{count:64b,Slot:6b,id:"minecraft:redstone"},{count:64b,Slot:7b,id:"minecraft:redstone"},{count:64b,Slot:8b,id:"minecraft:redstone"},{count:64b,Slot:9b,id:"minecraft:redstone"},{count:64b,Slot:10b,id:"minecraft:redstone"},{count:64b,Slot:11b,id:"minecraft:redstone"},{count:64b,Slot:12b,id:"minecraft:redstone"},{count:64b,Slot:13b,id:"minecraft:redstone"},{count:64b,Slot:14b,id:"minecraft:redstone"},{count:64b,Slot:15b,id:"minecraft:redstone"},{count:64b,Slot:16b,id:"minecraft:redstone"},{count:64b,Slot:17b,id:"minecraft:redstone"},{count:64b,Slot:18b,id:"minecraft:redstone"},{count:64b,Slot:19b,id:"minecraft:redstone"},{count:64b,Slot:20b,id:"minecraft:redstone"},{count:64b,Slot:21b,id:"minecraft:redstone"},{count:64b,Slot:22b,id:"minecraft:redstone"},{count:64b,Slot:23b,id:"minecraft:redstone"},{count:64b,Slot:24b,id:"minecraft:redstone"},{count:64b,Slot:25b,id:"minecraft:redstone"},{count:64b,Slot:26b,id:"minecraft:redstone"},{count:0b,Slot:27b,id:"minecraft:redstone"}]}"""
    ]

    @staticmethod
    def fromSS(ss: int) -> str:
        return BARREL._barrelSS[ss]